# Generated by Django 4.0.3 on 2022-03-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('pic', models.ImageField(upload_to='image/')),
                ('report', models.FileField(upload_to='files/')),
            ],
        ),
    ]
